- adyen.php
- controllers/FrontController.php
- controllers/admin/AdminAdyenPrestashopCronController.php
- controllers/admin/index.php
- controllers/front/Notifications.php
- controllers/front/Payment.php
- controllers/front/ThreeDSProcess.php
- controllers/front/Validate3d.php
- helper/Configuration.php
- helper/Data.php
- service/ClientFactory.php
- service/Configuration.php
- service/notification/NotificationProcessor.php
- service/notification/NotificationReceiver.php
- tests/service/Adyen/Service/CronControllerTest.php
- tests/service/Adyen/Service/NotificationReceiverTest.php
- tests/service/Adyen/Service/unprocessed-notification.json
- Add new admin controller which the cronjob can use to process
notifications
- Rename notificationProcessor to notificationReceiver because it
handles receiving and saving notifications
- Fix for ajaxRender: exit after rendering
- Fix for ajaxRender: set this->ajax to true by default
- Fix for try catches: if catch triggered, return something ot exit to
prevent errors
- Create Configuration class for global settings
- Fix for link generation: burnt in links are not working since
friendly url setting overwrites the default url structure and triggers
error when trying to open an 'old' link
- add installTab and createCronJobToken to upgrade 1.0.1
- process authorisation notifications - adding a message if processed
- expose admin controller for cron jobs to call
> PW-1556 execute notifications

- adyen.php
- helper/Data.php
Since this value is not set before installing the plugin the plugin doesn't show up in the modules list, therefore we provide a default value for the ADYEN_MODE configuration.
> Fix for fresh install when ADYEN_MODE is empty

- controllers/front/ThreeDSProcess.php
As of now, our PrestaShop plugin would show a blank page with a JSON with the error message. This is because the back-end would send an empty response with a 200 status code, tricking the front-end into treating this as a successful payment.
Changing the action of this response to `error` will inform the front-end how to properly handle this issue.
> PW-1891 Treat a `Refused` error code for 3DS process

- css/adyen.css
- views/templates/front/payment.tpl
Since PrestaShop uses Bootstrap on the default theme, removing CSS properties from our custom CSS will make customization easier.
> Use simpler CSS for errors

- composer.json
According to the [PrestaShop documentation and the code validator](https://devdocs.prestashop.com/1.7/modules/concepts/composer/#important-notes), the `prepend-autoloader` property needs to be set to `false` in the `composer.json` file, otherwise it might break the PrestaShop instance.
> Remove `prepend-autoloader` option

- .github/index.php
- application/index.php
- controllers/index.php
- exception/index.php
- index.php
- service/adapter/classes/index.php
- service/adapter/classes/order/index.php
- service/adapter/index.php
- service/index.php
- service/modification/exception/index.php
- service/modification/index.php
- service/notification/index.php
- tests/helper/index.php
- tests/index.php
- tests/modification/index.php
- tests/service/Adyen/Service/index.php
- tests/service/Adyen/index.php
- tests/service/index.php
- upgrade/index.php
- views/img/index.php
- views/index.php
- views/js/index.php
- views/js/payment-components/index.php
According to the PrestaShop Code Validator, having an index.php file in each directory helps with the e-commerce security.
These files were added with the [autoindex](https://github.com/jmcollin/autoindex) package.
> Add index.php files to directories

- views/templates/front/adyencheckout.tpl
- views/templates/front/card-payment-method.tpl
- views/templates/front/local-payment-method.tpl
- views/templates/front/order-confirmation.tpl
- views/templates/front/originkey-error.tpl
- views/templates/front/redirect.tpl
- views/templates/front/stored-payment-method.tpl
Wrapping the smarty strings in the translation function.
A new originkey-error template was created to include the same message in multiple templates.
Prestashop generates translations files when the localization form is filled. So unless the plugin needs to ship in multiple languages out of the box we do not need to add translation files.
Tested scenarios:
Triggered OriginKey error for payment methods.
Translated config titles in admin panel.
PS 1.7 and 1.6.
> [PW-2235]: Adding translations to smarty templates

- composer.json
- model/AdyenNotification.php
- service/notification/NotificationProcessor.php
- Take success field into consideration when processing the
notifications
- Add getProcessedNotificationsByMerchantReference() to retrieve a list
of already processed notifications for an order by merchant_reference
- Add hasProcessedAuthorisationSuccessNotification() to check if an
order has already had an Authorised notification with success = true
value processed
> [PW-2241] Update processing Authorisation and Offer_Closed notifications

- adyenofficial.php
BCMC works now only within the card component so hide the separate BCMC component for now until we implement the generic component and approach in ticket PW-2215
> [PW-2694] Hide BCMC until we implement generic component

- views/templates/front/adyencheckout.tpl
- views/templates/front/card-payment-method.tpl
- views/templates/front/get-started.tpl
- views/templates/front/local-payment-method.tpl
- views/templates/front/order-confirmation.tpl
- views/templates/front/redirect.tpl
- views/templates/front/stored-payment-method.tpl
Fix issue with the PrestaShop code validator, enforcing a character set to all variables used in template files.
Submitted the plugin to the PrestaShop Validator website
> Fix escaping for the PrestaShop validator

- service/modification/Refund.php
PrestaShop refunds do not work for shipping costs, only for the costs of a product.
Refund shipping costs in PrestaShop 1.6 and 1.7
> [PW-2731] Fix refund with shipping costs

- service/notification/NotificationProcessor.php
Only move orders to paid during processing notifications when the order has specific states 
An Authorisation success = true notification should only move an order state to paid when it's canceled, error or waiting for payment
In case the order is already paid or moved to another state, the notification effect will be ignored
With this approach multiple state switching and email sending can be avoided
Fixes #110
> [PW-2926] Plugin change 2 times the command status

- model/AdyenPaymentResponse.php
- views/js/payment-components/card-payment-method.js
- views/js/payment-components/local-payment-method.js
- views/js/payment-components/stored-payment-method.js
If there's some network latency the user could spam Pay button in prestashop version 1.6, this will result in multiple transactions being made. Adding a spinner and disabling the button after the first click to avoid such issues.
1.6 and 1.7
Valid, invalid cards, non3DS, 3DS2
Valid, invalid stored payment methods
Local payment methods 
Fixes #100 #106
> [PW-2779] Adding disabling button after click on Pay

- controllers/front/Payment.php
The current calculation sends information as a floating point number, which is incorrect and prone to issues when dealing with non-exact costs (€8.05, for example).
To fix this, we are formatting the number we get as shipping costs from PrestaShop and formatting it to cents before sending it to Adyen servers.
Selected Klarna Pay Now in the checkout process. Before the fix, it was impossible to move on if the cost was not round (tested with shipping costs of €8.05). After the fix, user is redirected.
**Fixed issue**:  PW-2997
> Fix open invoice line item for shipping costs

- views/js/checkout-component-renderer.js
Adyen Components have protection from cloning nodes in place which interferes with the modal component in PrestaShop 1.6. To make it work with Fancybox we have changed the order of rendering the components and modal, but this introduced an issue where the modal could not be resized.
This pull request will make the modal a fixed size. This is due to a limitation in the technologies present and there's no way of changing this without over-engineering a component that reads the size of the contents of the iframe, which will probably not going to work in every case anyways.
If there's the requirement of making it more flexible we can introduce configuration to allow implementations of the plugin to determine the size of the modal.
Payment with 3DS2 cards in PrestaShop 1.6 and 1.7.
> Set fixed dimensions for the 3DS2 modal in PrestaShop 1.6

- adyenofficial.php
- views/js/checkout-component-renderer.js
- views/templates/front/adyencheckout.tpl
In prestashop 1.6 the `prestashop` variable is not available on the frontend containing the addresses and other details for the cart. In order to render the checkout component correctly we need at least the country code on the frontend.
In the PR the country code and the required billing address details are passed to the frontend and used as default parameters. In case the `prestashop` object is available it will override these default values otherwise it will be used by the components.
Oney on 1.6 and 1.7
> Prefill the billing address and country code in 1.6 on the frontend

- controllers/FrontController.php
Use ajaxRender when available otherwise fall back to ajaxDie
ajaxRender has been introduced in prestashop version 1.7.5 and not in
1.7, before 1.7.5 only ajaxDie is available
card payments with 1.7 and 1.6
#132 [PW-3329] Call to undefined method ModuleFrontController::ajaxRender
> [PW-3329] Call to undefined method ModuleFrontController::ajaxRender

- model/Hashing.php
Fixing error: Case mismatch between loaded and declared class names: "Adyen\PrestaShop\model\Hashing" vs "Adyen\PrestaShop\Model\Hashing"
#136
> [PW-3448] Fix namespace 'Case mismatch'

- service/notification/NotificationProcessor.php
When processing an Adyen notification, in case the merchant reference is a valid cart number for a non Adyen method paid order then it can change the order itself. A non Adyen method paid order should not be affected by an Adyen notification.
Failed payment with Adyen payment method and successful payment with a non Adyen method 1.7 and 1.6 -> A non Adyen payment method should bump the cart number therefore the notification cannot arrive with the same merchant reference as another payment method, tested with card and redirect payment method (iDeal)
Failed payment with Adyen payment method and successful payment with a non Adyen method 1.7 and 1.6, manually changed the merchant reference to test if the notification can change the order for a non Adyen method.
#131 …
> [PW-3315] Order status changed by notifications even if the payment method has been changed

- service/adapter/classes/Configuration.php
Parameters for methods `getEncryptedAPIKey`, `getClientKey` and `isTestMode` are not used anymore.
None.
> Clean up unused parameters

- helper/Data.php
- service/builder/Customer.php
If `shopperReference` is shorter than 3 characters, Adyen will not store payment methods even when asked to do so. This commit fixes this issue by prepending characters to the field without breaking the feature for shoppers who already have cards stored.
* Payment with credit card while asking to save the payment method.
* See stored payment method in payments list.
> Fix `shopperReference` length

- adyenofficial.php
- service/Client.php
- service/adapter/classes/Configuration.php
Allow the merchant to specify his integrator name. If this field is populated, it is added to the request under the applicationInfo. If not, the field is not sent .
Tested both scenarios on both 1.6 and 1.7.
Requests with an integrator setting sent the Integrator correctly in the request.
Requests without an integrator setting sent no Integrator/empty string.
> [PW-2852] Gather integrator in applicationInfo

- model/AdyenNotification.php
- service/notification/NotificationProcessor.php
- Always prioritize the data received from the payment details call, over the data received in the notification call.
- Delay the processing of an `authorization w/success = false` notification by an hour 
1. Successful authorization notification processed after order is already set to successful. No changes.
2. Not successful authorization notification processed after order is already set to successful. Order status **not** updated
3. Not successful authorization notification processed after order is already set to cancelled. No changes.
#130
> [PW-3316] Incoherence between order status from notifications system and payment response handling

- adyenofficial.php
- controllers/FrontController.php
- controllers/front/PaymentsDetails.php
- views/js/checkout-component-renderer.js
New paypal integration on prestashop. The main difference to other payment methods was that we were required to use the `handleAction` and not the `createFromAction`.
The other main change was to implement the `onCancel` function which sends a request to the payment details endpoint with an additional parameter. Because of this parameter, the back end will set the order to cancelled and return an appropriate message.
Happy flow on 1.6 and 1.7
Unhappy flow on 1.6 and 1.7
> [PW-2767] - New paypal integration 

- adyenofficial.php
- controllers/FrontController.php
- controllers/front/Payment.php
- controllers/front/PaymentsDetails.php
- controllers/front/Result.php
- model/AdyenPaymentResponse.php
- service/adapter/classes/Configuration.php
- upgrade/upgrade-3.3.0.php
Add ADYEN_OS_PAYMENT_NEEDS_ATTENTION new order status
Alter adyen_payment_response to add request_amount and request_currency 
Create waiting for payment orders for RedirectShopper methods
Avoid creating order in case the cart amount or currency has changed during the payment process
In case the payment is verified and the cart has changed, flag the order as needs attention
#151 [PW-3952] Bank amount different of prestashop total paid amount
> [PW-3952] Validate cart value and currency before each /payments and /payments/details request

- adyenofficial.php
After saving the configuration on Prestashop, some sensitive fields such as HMAC key becomes visually empty and only shows a green outline, which is confusing as green outline feels like it is ready to receive some input. API key has a small reminder underneath the field, yet other fields do not have that and confuses the merchants.
Hence, a **message should be added similar to the (API key one)** to make it clear that the value has been saved. Message should also be translatable.
> [PW-3883] - Prestashop configuration fields are being visually empty after saving 

- adyenofficial.php
1. Search for ->l( functions in the codebase and check if the translation is used correctly.
3. Fix the usage if incorrect
4. Check if the translation shows up in the admin where the translation can be added
**Invalid translation definition:**
- Any translation containing a variable may [yield unexpected results](https://devdocs.prestashop.com/1.7/modules/creation/module-translation/classic-system/#limitations-and-caveats)
- Any translation [containing a new line](https://github.com/PrestaShop/PrestaShop/issues/11573) between the opening bracket and the first quote will not be translatable
- Any translation containing a double quoted string ie. $this->l("Test string")will not be translatable
> [PW-4033] - Fix translations everywhere in the plugin where it's incorrect 

- controllers/admin/AdminAdyenOfficialPrestashopCronController.php
- service/notification/NotificationProcessor.php
- tests/service/Adyen/Service/NotificationProcessorTest.php
When processing authorisation w/ `success = true`, verify that the notification amount, order and cart amounts are all equal. If one of these fields does not match, flag it with the `ADYEN_OS_PAYMENT_NEEDS_ATTENTION` status.
* Manually updated notification amount after order was completed
* Manually updated order amount after order was completed
> [PW-3960] - Verify the paid amount during notification processing 

- helper/Data.php
The current prestashop plugin sends the `shopperReference` for both logged in and guest users, since the platform automatically creates a customer for guest users. Hence, we should check if the customer is a guest user and if so, **do not send** the `shopperReference` parameter. Otherwise, this parameter should be normally sent.
- Logged in scenario
- Guest user scenario
> [PW-2374] -  Do not send shopperReference for guest users in the /paymentMethods request

- controllers/admin/AdminAdyenOfficialPrestashopCronController.php
When the cron is successfully completed, return some message which enables the merchant to verify and make sure that the it was successfully executed.
Return message: **Cron job finished successfully**
- All notifications successfully processed outputs aforementioned message
- A notification was not successfully processed outputs error message
> [PW-2401] - Return a success message for cronjob after run

- adyenofficial.php
- controllers/FrontController.php
Based on http://doc.prestashop.com/display/PS16/Module+translation on 1.6 we cannot use the ->l() function in the FrontController. Instead $this->module->l() should be used.
- Failed payment, error message correctly shown on 1.7
- Failed payment, error message correctly shown on 1.6
> [PW-4115] - Modify how the translate function is called in the FrontController 

- service/RefundService.php
- service/modification/Refund.php
- tests/modification/RefundTest.php
Currently when an order slip is to be created, if the shipping_amount exists, it is always added to the OrderSlip amount:
```
if (!empty($orderSlip->shipping_cost_amount)) {
$fullRefundAmount += $orderSlip->shipping_cost_amount;
}
```
Hence, instead of checking the amount, the `shipping_cost` flag should be set. This will be set whenever the merchant selects to also refund the shipping amount, from the admin interface.
Also, because of [this issue](https://github.com/Adyen/adyen-prestashop/issues/147) the amount sent to Adyen should be capped, to ensure that the merchant does not attempt to refund a larger amount than the customer actually paid. This issue has [already been identified](https://github.com/PrestaShop/PrestaShop/issues/18319) on prestashop side. This solution should be …
> [PW-4153] - Correctly check if shipping_cost should be added to OrderSlip

- adyenofficial.php
- helper/Data.php
In case the mode is production and the live url prefix is empty the module shows an exception which is thrown by the library. In order to avoid this certain scenario the live url prefix is required from now on.
In case an (network or other non Adyen related) error shows up during the payment methods request we catch all these to avoid showing it on the frontend and instead we just log it in the error.log file in the adyen folder.
> Fix error message in case of missing live url prefix

- controllers/FrontController.php
- service/Cart.php
- views/js/checkout-component-renderer.js
In 1.7 when the customer has an error during the redirection, they are sent back to a blank error page. Instead, we should redirect them back to the payment methods page and show an error message.
* Happy flow on 1.6, 1.7
* Error during redirection on 1.7 which displays the previously mentioned message
* Error during redirection on 1.6
> [PW-3071] - How to implement a nicer error page than the current in 1.7

- adyenofficial.php
- service/notification/NotificationProcessor.php
In the [check](https://github.com/Adyen/adyen-prestashop/blob/develop/service/notification/NotificationProcessor.php#L388-L397) which compares the amounts and currencies, we should make the following changes:
* Double check if order values should be validated as well or only cart details should
* Log the cart and order details (similar to `FrontController::validateCartOrderTotalAndCurrency`)
* Process notification after normal payment on 1.7
* Process notification after 3DS payment on 1.7
* Process notification after 3DS payment on 1.6
> [PW-4295] - Update payment needs attention check

- adyenofficial.php
- views/css/adyen.css
- views/js/checkout-component-renderer.js
- views/templates/front/payment-method.tpl
- views/templates/front/stored-payment-method.tpl
Copy the default html structure of a default payment method when displaying our payment methods.
It helps our merchants with the customization, templates and styling.
* Payment methods clearly shown on 1.7
* Payment methods clearly shown on 1.6
> [PW 2778] - Display the payment methods as the default payment methods 

- views/js/checkout-component-renderer.js
Fix prestashop pay button visibility in 1.7
In case the user is using a non adyen payment method or a stored payment
from adyen the pay button can remain hidden if a prior selected payment
method hides it
Switching payment methods using adyen wallet payment methods, stored, normal payment methods and non adyen payment methods
> [PW-4312] Order button not shown

- controllers/FrontController.php
- service/Order.php
- service/notification/NotificationProcessor.php
Stop using setCurrentState() and update the order history with own logic
Introduce updateOrderState() in the orderService
Replace all setCurrentState with new updateOrderState()
Update transaction_id with the the original pspreference
> [PW-4350] Multiple order_payments created on redirect

- adyenofficial.php
- upgrade/upgrade-3.4.0.php
- views/js/checkout-component-renderer.js
- views/templates/front/adyencheckout.tpl
New configuration to toggle stored payment methods is added to the admin configuration panel
In case it's enabled the customer (if logged in) can store and use stored payment methods
In case it's disabled no one click payment method can be stored or used
> [PW-4246] Add new enable stored payment methods configuration field

- views/js/checkout-component-renderer.js
This fixes an issue in the Checkout page for the plugins. When one of the payment methods is set to valid, you could click the payment button or select a different payment method and finish the transaction without triggering the validation a second time.
This commit changes the flag that allows a payment to proceed to an object that holds states for different payment methods.
For both PrestaShop 1.6 and 1.7:
- Switching payment methods and trying to pay
- Pay without switching payment methods
> Fix validation for payment methods

- adyenofficial.php
- service/Client.php
- service/Logger.php
We should log certain logs (depending on severity) using the prestashop functionality so that our merchants could get a better understanding about what's happening in the plugin when accessing the prestashop logs page. Only log the errors, warnings and major issues. Informative ones can still be just stored in the log files. `PrestaShopLoggerCore::addLog` function can be used to add logs to this page.
* Error message logged
* Warning message logged
> [PW-4199] - Use prestsahop logs page for easier log access

- adyenofficial.php
- controllers/admin/AdminAdyenOfficialPrestashopLogFetcherController.php
- views/css/adyen_admin.css
- views/templates/admin/log-fetcher.tpl
We see it as a huge scaling blocker, especially with smaller merchants, that they have no technical knowledge and technical functionality such as retrieving the log files. This ends up taking quite some time for them. (No server access, no developer, hosting provider not providing sftp etc)
Beside showing the critical errors in the prestashop logs table we should provide them a tool to zip and download all the log files (maybe also a txt with some useful information - plugin version, prestashop version, time etc)
**Steps**:
1. Create a new controller
1. Add this new functionality as a tab, as shown here
1. When this controller is accessed the logs should be downloaded automatically
Download logs on 1.6
Download logs on 1.7
> [PW-4200] - Create download logs button

- adyenofficial.php
On the adyen module configuration page, update the hint fields to be more clear and consistent. See below the text to update:
1. **Merchant Account:** In your Adyen Customer Area you have a company account and under that a merchant account. Fill in the merchant account name.
1. **API Key test:** Enter your test API Key. This can be generated in your test Customer Area > Account > API Credentials.
1. **API Key live:** Enter your live API Key. This can be generated in your live Customer Area > Account > API Credentials. During testing, this field should be populated with dummy data.
1. **Client Key live:** The client key is used to authenticate requests from your payment environment. This can be generated in your live Customer Area > Account > API Credentials. During testing, this field …
> [PW-4649] - Update Prestashop Config panel

- service/Cart.php
On 1.6, the cart quantity in the header (shown in attached image) is set as a smarty variable in the PrestaShop `FrontController::init` function, by calling `(int)$cart->nbProducts()` on the context cart. However in this particular case, after a redirection which was failed/cancelled, the context cart is re-created only in the adyen front controller (by calling the the `cloneCart` function).
Hence on the first page load after a failed payment, the cart quantity in the prestashop controller will be set to 0, since the proper cart is created later in the flow, in the adyen controller. So the interface will show an empty cart, even though in reality the cart is not empty. After a refresh, the interface successfully loads the number of items in the cart. 
To solve this issue, we should set …
> [PW-4734] - 1.6 - Set cart product quantity when cart gets cloned 

- adyenofficial.php
- controllers/FrontController.php
- service/Cart.php
Currently, in the `Cart::cloneCart` function, we do not set the `cart->id_address_delivery` and the `cart->id_invoice_delivery`.
In some cases, when a failed transaction is redirected and if there are multiple addresses, these 2 address fields will not be correctly set and hence the user will have to restart checkout from the address page, with no info regarding the failed payment. If the customer only has a single address available, this is not an issue.
Hence we need to set these 2 fields when cloning the cart, so the customer is redirected back to the payments page.
**Steps:**
1. Set the `cart->id_address_delivery` and the `cart->id_invoice_delivery` fields in the `Cart::cloneCart` function.
E2E tests
> [PW-4781] - Set addresses when cloning cart

- views/js/checkout-component-renderer.js
- views/templates/front/adyencheckout.tpl
On 1.6, if the merchant enables quick (one-page) checkout, the js in the checkout-component-renderer.js file is not executed at all.
The `ADYEN_CHECKOUT_CONFIG` is required for the **checkout-component-renderer** to function. Currently, this is set when the `hookDisplayPaymentTop` action is called.
However if one-page checkout is enabled, once the checkout page is loaded, `hookDisplayPaymentTop` is not executed, which implies that the `window.ADYEN_CHECKOUT_CONFIG` in the **checkout-component-renderer** will be set to null and so it will return without executing this js file.
Once the user fills in his guest checkout details and chooses the carrier, the payment options will be loaded, at which point the `hookDisplayPaymentTop` will be executed. However, since we do not call the …
> [PW-4635] - One-page checkout issue on 1.6

- adyenofficial.php
- service/Checkout.php
The PrestaShop plugin makes unnecessary requests to the `/paymentMethods` Adyen endpoint. The requests are all done by the `fetchPaymentMethods` function in the adyenofficial file. This function is called by the following hooks:
* hookDisplayPaymentTop
* hookPaymentOptions (1.7)
* hookPayment (1.6)
Currently, for a single transaction the following api calls are done:
* 1.7 - **4 calls** to /paymentMethods
* 1 in `hookDisplayPaymentTop`
* 3 (1 for each of the 3 steps when already signed in) in `hookPaymentOptions`
* 1.6 (5-page checkout) - **2 calls** to /paymentMethods
* 1 in `hookDisplayPaymentTop`
* 1 in `hookPayment`
* 1.6 (1-page checkout) - **3 calls** to /paymentMethods
* 2 in `hookDisplayPaymentTop`
* 1 in `hookPayment`
After this PR is merged:
* 1.7 - **1 call** to …
> [PW-4456] - Reduce the number of requests to /paymentMethods 

- adyenofficial.php
- upgrade/upgrade-3.7.0.php
- views/css/adyen.css
- views/js/adyen-admin.js
A new configuration value to enable/disable the adyen styling should be created. When enabled, the adyen css file will be loaded whereas it won't be loaded if the config is disabled. This will help merchants that want to style the checkout page themselves, by not applying the styling of our files.
* Config enabled
* Config disabled
> [PW-4877] - Create configuration for adyen styling

- service/Client.php
The payment source application information field duplicates the merchant application and not necessary
anymore. See [docs page](https://docs.adyen.com/development-resources/building-adyen-solutions#building-a-plugin)
> [PW-5091] Do not set payment source application information

- adyenofficial.php
- upgrade/upgrade-3.7.1.php
The **WAITING_FOR_PAYMENT** order state should have a logable value of 0. This should be done since when the order is in this status, no payment has been processed yet and hence, no OrderPayment linked to this order should be created. This will also ensure that the `total_paid_real` db value, will only be updated once the payment actually goes trough, and not during the redirection.
**Steps:**
1. When creating the WAITING_FOR_PAYMENT state, set the `logable` value to 0.
3. Create upgrade script
* `total_paid_real = 0` during redirection on 1.6
* `total_paid_real = 0` during redirection on 1.7
#192
> [PW-4943] - Update logable value of our WAITING_FOR_PAYMENT state

- .github/workflows/syntax-check.yml
Ubuntu 16.04 is deprecated so it needs to be moved to 18.04 in order to be able to run the test correctly
> Bump ubuntu version to 18.04

- .github/CODEOWNERS
- service/Checkout.php
Currently when a shopper is checking out with a virtual cart (all products to be bought are virtual) the adyen payment methods are not being fetched and displayed. This is due to a check on the delivery step of the checkout process, which on a virtual cart will not exist.
This PR will solve this issue by checking if the cart is virtual and if so, omitting the check on the delivery step.
* Checkout with a virtual cart
* Checkout with a normal cart
* Checkout with a mixed cart (1 virtual, 1 normal)
> [PW-6058] - Fetch payment methods on virtual cart

- adyenofficial.php
- controllers/admin/AdminAdyenOfficialPrestashopValidatorController.php
- service/adapter/classes/Configuration.php
Remove call of now removed Hook::getRetroHookName PS method from AdminAdyenOfficialPrestashopValidatorController
Fixes are tested on PrestaShop 8.0.1 and 1.7.8.8
**Fixed issue**:  [MAIN-1677](https://logeecom.atlassian.net/browse/MAIN-1677)
> Release version 4.0.5

- adyenofficial.php
- service/adapter/classes/Configuration.php
- service/builder/Payment.php
Google Pay button not showing on checkout.
Issue with missing request data for PayPal.
Fix is tested on PrestaShop 8.0.2.
**Fixed issue**:  (https://logeecom.atlassian.net/browse/CS-4395)
> Fix issues with GooglePay and PayPal
