controllers/front/Payment.php
views/templates/front/error.tpl

Fix error tpl
Fix an ajax return from Payment.php

Fixes during testing

---

controllers/front/Payment.php
controllers/front/Validate3d.php
helper/Data.php
service/adapter/classes/CustomerThreadAdapter.php
service/adapter/classes/order/OrderAdapter.php
service/notification/NotificationProcessor.php

- Create getTemplateFromModulePath helper function to retrieve the template path for both 1.6 and 1.7
- Add adapter classes for Order and CustomerThread classes

[PW-1741] Create adapter classes for Prestashop

---

adyen.php

This basically fixes most of the warnings from PhpStorm in the `adyen.php` file.

Tidying up the main class

---

adyen.php

This fixes installation issues with PrestaShop 1.6.
The exception treatment for `$refundService->request` is moved to the method itself.

Remove the `use` operator

---

adyen.php
application/VersionChecker.php
controllers/FrontController.php
controllers/front/Notifications.php
controllers/front/Payment.php
controllers/front/Result.php
controllers/front/ThreeDSProcess.php
controllers/front/Validate3d.php
helper/Data.php
service/adapter/classes/Configuration.php

- add isPrestashopSupportedVersion function in VersionChecker
- Remove unnecessary helper\Data initialisations
- Use versionChecker instead of helperData depricated isPrestashop16
function

Release 1.2.0 review

---

.travis.yml
adyen.php
controllers/front/Notifications.php
controllers/front/Payment.php
controllers/front/Validate3d.php
service/adapter/classes/Configuration.php
service/modification/Refund.php
service/notification/NotificationReceiver.php
tests/helper/DataTest.php
tests/modification/RefundTest.php
tests/service/Adyen/Service/NotificationReceiverTest.php
upgrade/upgrade-1.1.0.php
upgrade/upgrade-1.2.0.php
views/js/payment-components/credit-card.js
views/js/payment-components/local-payment-method.js
views/templates/front/local-payment-method.tpl

* Improve additional details handling
* Make tests easier
* Move variable instantiation

Refactor for end-to-end tests

---

adyen.php
helper/Data.php

Add reset function to handle reset only the parameters option
Fix reset "reset everything" option
Fix decrypt php error if parameter is empty

[PW-1883] Fix reset functionality for module

---

adyen.php
upgrade/upgrade-1.3.0.php

- Add upgrade 1.3 for creating waiting for payment order status
- Add createWaitingForPaymentOrderStatus function to create the new
order status
- During installation create the new order status
- During uninstall remove the configuration from the database

[PW-1925] Add new order status waiting for payment

---

controllers/front/Notifications.php
service/notification/NotificationReceiver.php

Decrypt HMAC key and notification password when validating notification
Save notification logs on the adyen_notification level

Fix notification receiver due to new encryption

---

adyen_official.php
views/templates/front/card-payment-method.tpl
views/templates/front/error.tpl
views/templates/front/local-payment-method.tpl
views/templates/front/stored-payment-method.tpl

Release notes:
Because of this change anyone who had the previous versions installed needs to reinstall and reconfigure the plugin

[PW-2198] Change name to adyen_official

---

composer.json

Use it to add index.php for all the folders in your prestashop module

Add prestashop/autoindex to composer require-dev

---

README.md
adyenofficial.php
composer.json
controllers/FrontController.php
controllers/admin/AdminAdyenPrestashopCronController.php
controllers/front/Notifications.php
controllers/front/Payment.php
controllers/front/Result.php
controllers/front/ThreeDSProcess.php
controllers/front/Validate3d.php
helper/Data.php
service/Order.php
service/adapter/classes/Configuration.php
service/notification/NotificationProcessor.php
tests/service/Adyen/Service/NotificationProcessorTest.php
views/css/adyen.css
views/js/payment-components/order-confirmation.js
views/templates/front/card-payment-method.tpl
views/templates/front/error.tpl
views/templates/front/local-payment-method.tpl
views/templates/front/order-confirmation.tpl
views/templates/front/stored-payment-method.tpl

Rename module to adyenofficial from adyen_official
#70 Add prestashop/autoindex to composer require-dev 
#67 [PW-1732] Banktransfer support

Release 2.1.0

---

README.md

Update Readme with docs link and remove duplicated info

[PW-1890] Update ReadMe

---

adyenofficial.php

Replace path in addCSS() and registerJavascript() to support multistores
$this->_path contains the store which works only for 1 store and not for
multistore setups

[PW-2058] Fix prestashop plugin integration with multi stores setup 

---

adyenofficial.php
views/templates/front/get-started.tpl

Here we're adding a header with useful links to the module's configuration panel

[PW 2234]: Configuration panel header

---

infra/NotificationRetriever.php
views/templates/front/adyencheckout.tpl
views/templates/front/card-payment-method.tpl
views/templates/front/local-payment-method.tpl
views/templates/front/redirect.tpl
views/templates/front/stored-payment-method.tpl

Escape smarty template variables
Use intval() for sql query

[PW-2343] Meet prestashop validation requirements

---

adyenofficial.php
upgrade/upgrade-2.1.3.php

**Description**
When changing the plugin name to publish it in the PrestaShop Addons Marketplace, there was some code left referencing the old plugin name. It was also forgotten to add the crontab for the new plugin name.
**Tested scenarios**
Update the plugin version
**Fixed issue**:  #83

[PW-2399] Add upgrade script to fix v2 changes

---

adyenofficial.php
service/adapter/classes/Configuration.php
upgrade/upgrade-2.1.3.php

**Description**
Release version 2.1.3
**Tested scenarios**
End to end tests without developer dependencies.

Release 2.1.3

---

adyenofficial.php
service/Order.php
service/notification/NotificationProcessor.php

Please read commit messages
banktransfer_IBAN notification processing

[PW-2492] Fix Refunds - Step 3

---

.github/CODEOWNERS
adyenofficial.php
infra/NotificationRetriever.php
service/Order.php
service/RefundService.php
service/adapter/classes/Configuration.php
service/notification/NotificationProcessor.php
upgrade/upgrade-2.1.3.php
views/templates/front/adyencheckout.tpl
views/templates/front/card-payment-method.tpl
views/templates/front/get-started.tpl
views/templates/front/local-payment-method.tpl
views/templates/front/order-confirmation.tpl
views/templates/front/redirect.tpl
views/templates/front/stored-payment-method.tpl

Release the version 2.1.4 to the master branch.

Release 2.1.4

---

adyenofficial.php
service/adapter/classes/Configuration.php
service/modification/Refund.php

Fix refund with shipping costs (#99)

Release 2.1.5

---

adyenofficial.php
model/AdyenPaymentResponse.php
service/adapter/classes/Configuration.php
service/notification/NotificationProcessor.php
views/js/payment-components/card-payment-method.js
views/js/payment-components/local-payment-method.js
views/js/payment-components/stored-payment-method.js

#112 [PW-2926] Plugin change 2 times the command status
#111 [PW-2779] Adding disabling button after click on Pay
**Fixed issues**:  
#100 [PW-2779] Adding a spinner/disabling button after click on Pay
#106 [PW-2817] 5 times the same order in the same second
#110 [PW-2926] Plugin change 2 times the command status

Release 2.1.6

---

adyenofficial.php

Load the logos from the checkout-shopper Adyen url.

[PW-3179] Add logos for payment methods

---

views/css/adyen.css

Fix label margin to have the same start from the left as the box

---

adyenofficial.php
service/adapter/classes/Configuration.php
views/css/adyen.css

#125 [PW-3179] Add payment method logos
#129 Fix label margin to have the same start from the left as the box
Logos on 1.6 and 1.7

Release 3.1.0

---

controllers/FrontController.php
views/js/checkout-component-renderer.js

Add Pending resultCode handling
Show popup when action.type is await
1.6 and 1.7

Add Blik support

---

views/js/checkout-component-renderer.js

Support Giropay via simple redirect instead of component
1.6 and 1.7

Add Giropay support

---

adyenofficial.php
helper/Data.php
service/adapter/classes/Configuration.php
service/builder/Customer.php

#143 [PW-3637] Clean up unused parameters 
#144 [PW-3619] Fix `shopperReference` length 
End to end tests
Fixes: #145 Vendor folder missing

Release 3.2.1

---

.github/CODEOWNERS

Add @Morerice to the list of owners

Add @Morerice to the list of owners

---

adyenofficial.php
controllers/FrontController.php
service/Cart.php
views/js/checkout-component-renderer.js
views/templates/front/payment-method.tpl

Since #149 we started removing the payment method if isAvailable is false, both on 1.6 and 1.7:
```
.catch(e => {
if (IS_PRESTA_SHOP_16) {
const paymentRow = paymentForm.closest('.adyen-payment');
paymentRow.remove();
} else {
const payWithOption = paymentForm.closest('.js-payment-option-form');
const paymentOption = payWithOption.prev();
paymentOption.remove();
payWithOption.remove();
}
});
```
However on 1.6, the mutationObserver below will call the `renderPaymentMethods` whenever a mutation is observed, such as when a payment method is removed.
```
// Callback function to execute when mutations are observed
const callback = function(mutationsList, observer) {
// Use traditional 'for loops' for IE 11
for (const mutation of mutationsList) {
if (mutation.type === 'childList') {
// The …
```

[PW-4243] - Do not remove paymentRow on 1.6

---

adyenofficial.php

Make client key test and live configuration field required in the configuration page

Make client key configuration required

---

adyenofficial.php
controllers/FrontController.php
service/Cart.php
service/RefundService.php
service/adapter/classes/Configuration.php
service/modification/Refund.php
tests/modification/RefundTest.php
upgrade/upgrade-3.3.0.php
views/js/checkout-component-renderer.js
views/templates/front/payment-method.tpl

#163 [PW-4153] - Correctly check if shipping_cost should be added to OrderSlip
#164 [PW-4195] -  Fix error message in case of missing live url prefix
#165 [PW-3071] - How to implement a nicer error page than the current in 1.7
#166 [PW-4243] - Do not remove paymentRow on 1.6
E2E tests
#147 Shipping fees are refunded twice

Release 3.3.1

---

adyenofficial.php
service/adapter/classes/Configuration.php
service/notification/NotificationProcessor.php

#170 [PW-4295] - Update payment needs attention check
E2E tests

Release 3.3.2

---

adyenofficial.php

Update cron token configuration field
Generate shorter token upon installation
Generate new token when saving an empty value
Added hint
Empty token saving
Custom token saved

[PW-4378] Generate shorter only hex cron token

---

views/js/checkout-component-renderer.js
views/templates/front/adyencheckout.tpl

For some payment flows this might be a required configuration field

Add totalPriceLabel configuration for apple pay component

---

adyenofficial.php
upgrade/upgrade-3.4.0.php

Add auto cron job runner configuration to the admin
Add upgrade script to set default value for the new configuration
Also outsource the creation of default configurations to a new function: createDefaultConfigurations() upon installation
Rename configuration ADYEN_AUTO_CRONJOB_RUNNER to ADYEN_AUTO_CRON_JOB_RUNNER

Add auto cron job runner configuration to the admin

---

adyenofficial.php
controllers/admin/AdminAdyenOfficialPrestashopController.php
controllers/admin/AdminAdyenOfficialPrestashopLogFetcherController.php
controllers/admin/AdminAdyenOfficialPrestashopValidatorController.php
helper/Data.php
service/Client.php
service/Logger.php
service/adapter/classes/Configuration.php
views/css/adyen_admin.css
views/js/checkout-component-renderer.js
views/templates/admin/log-fetcher.tpl
views/templates/admin/validator.tpl

#184 [PW-4443] - Fix validation for payment methods
#185 [PW-4200] - Create download logs button
#186 [PW-4199] - Use PrestaShop logs page for easier log access
#189 [PW-4260] - Create a validate button for module installation
E2E tests

Release 3.5.0

---

.github/CODEOWNERS

The thyme has come

---

.github/CODEOWNERS
adyenofficial.php
controllers/FrontController.php
override/classes/order/OrderHistory.php
service/Cart.php
service/Client.php
service/Logger.php
service/Order.php
service/adapter/classes/Configuration.php
upgrade/upgrade-3.6.0.php
views/templates/email/waiting_for_payment_adyen.html
views/templates/email/waiting_for_payment_adyen.txt

#195 & #199 [PW-4368] - Waiting for payment email
#196 [PW-4649] - Update Prestashop Config panel 
E2E tests

Release 3.6.0

---

README.md
views/js/checkout-component-renderer.js

Update README file with currently supported payment methods

[PW-3648] - Update README with supported payment methods

---

CHANGELOG.MD

Add changelog file to guide merchants who downloads the plugin via the marketplace and not aware of the github repo

Add CHANGELOG.MD file

---

CHANGELOG.MD
README.md
adyenofficial.php
controllers/FrontController.php
controllers/admin/AdminAdyenOfficialPrestashopValidatorController.php
service/Cart.php
service/Checkout.php
service/adapter/classes/Configuration.php
upgrade/upgrade-3.7.0.php
views/css/adyen.css
views/js/adyen-admin.js
views/js/checkout-component-renderer.js
views/templates/front/adyencheckout.tpl

#202 [PW-4781] - Set addresses when cloning cart
#205 [PW-4635] - One-page checkout issue on 1.6
#203 [PW-4695] - Create smaller sections in configuration panel
#204 [PW-3648] - Update README with supported payment methods
#207 [PW-4456] - Reduce the number of requests to /paymentMethods
#208 [PW-4877] - Create configuration for adyen styling
E2E tests

Release 3.7.0

---

README.md

Double check the prestashop compatibility texts -> should be 1.6.1 - 1.7 on README. Also adopt identical structure of the README to the shopware6 plugin.

[PW-4908] - Double check README compatibility texts

---

adyenofficial.php
controllers/front/Payment.php
service/Payment.php
service/adapter/classes/Configuration.php
service/builder/Customer.php
views/js/checkout-component-renderer.js

- Fix issue with disabled place order button
- Fix issue with valid/invalid component state on checkout
- Fix issue with missing shopperName/lineItems in payment request data
- Update plugin version to 4.0.6.
Fixes are tested on PrestaShop 8.0.1 and 1.7.8.8
**Fixed issue**:  [CS-4395](https://logeecom.atlassian.net/browse/CS-4395), [CS-4375](https://logeecom.atlassian.net/browse/CS-4375), [CS-4431](https://logeecom.atlassian.net/browse/CS-4431)

Release version 4.0.6
